name: Validate Helloworld2 Proxy

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make smoke test executable
        run: chmod +x ./tests/helloworld2/smoke-test.sh
      - name: Run smoke test
        run: bash ./tests/helloworld2/smoke-test.sh
